cmake_minimum_required(VERSION 3.13)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CROSS_COMPILE_TOOLCHAIN_PREFIX "aarch64-poky-linux")
set(CMAKE_CROSSCOMPILING_EMULATOR qemu-aarch64)

set(CROSS_ROOT "/opt/cross/${CROSS_COMPILE_TOOLCHAIN_PREFIX}")
set(CROSS_SYSROOT "${CROSS_ROOT}/${CROSS_COMPILE_TOOLCHAIN_PREFIX}/sysroot")

set(CMAKE_C_COMPILER   "${CROSS_ROOT}/bin/${CROSS_COMPILE_TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${CROSS_ROOT}/bin/${CROSS_COMPILE_TOOLCHAIN_PREFIX}-g++")
set(CMAKE_SYSROOT "${CROSS_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH "${CROSS_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(ENV{PKG_CONFIG_PATH}        "")
set(ENV{PKG_CONFIG_LIBDIR}      "${CROSS_SYSROOT}/usr/lib/pkgconfig:${CROSS_SYSROOT}/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CROSS_SYSROOT}")

find_program(CMAKE_C_COMPILER_LAUNCHER ccache)
find_program(CMAKE_CXX_COMPILER_LAUNCHER ccache)
